import {
    BookOpenText,
    Captions,
    FileVideo2,
    Link2,
    MicVocal,
    MonitorPlay,
} from 'lucide-react';

export const sourceIconItems = [
    {key: 'courses', Icon: BookOpenText, tone: 'bg-[#f4d98c] text-[#5c4214] dark:bg-[#f4d98c] dark:text-[#36240b]'},
    {key: 'lectures', Icon: MicVocal, tone: 'bg-[#b9dfd1] text-[#123f33] dark:bg-[#9bd9c2] dark:text-[#0b3026]'},
    {key: 'recordings', Icon: MonitorPlay, tone: 'bg-[#bfd7f3] text-[#183b61] dark:bg-[#a8caef] dark:text-[#102f50]'},
    {key: 'localMedia', Icon: FileVideo2, tone: 'bg-[#f3c2ac] text-[#642d1c] dark:bg-[#efb49a] dark:text-[#51210f]'},
    {key: 'subtitles', Icon: Captions, tone: 'bg-[#d6c7f2] text-[#3e2c68] dark:bg-[#c8b4ee] dark:text-[#2d1d55]'},
    {key: 'links', Icon: Link2, tone: 'bg-[#d0d9bc] text-[#344418] dark:bg-[#c1d49f] dark:text-[#27350f]'},
];

export const landingCopy = {
    en: {
        nav: {
            studyFlow: 'Study flow',
            noteQuality: 'Note quality',
            sources: 'Sources',
            openApp: 'Open app',
            startVideo: 'Start a video',
            startShort: 'Start',
        },
        controls: {
            languageLabel: 'Language',
            themeLabel: 'Toggle dark mode',
            switchToEnglish: 'Switch homepage language to English',
            switchToChinese: 'Switch homepage language to Chinese',
            useLight: 'Use light mode',
            useDark: 'Use dark mode',
        },
        hero: {
            eyebrow: 'Long-video study notes',
            title: 'Turn long videos into study-ready notes first.',
            desc: 'Upload a course, lecture, recording, or video link. FluentFlow prepares the note, transcript, and key moments before you study.',
            primary: 'Start processing',
            secondary: 'See the study flow',
            note: '',
        },
        heroVisual: {
            label: 'Animated product walkthrough: input a long video, process source material, study beside the note, and export review assets',
            path: 'fluentflow.app/video-note',
            inputStep: 'Input',
            processingStep: 'Processing',
            studyStep: 'Study / Review',
            exportStep: 'Export',
            upload: 'Upload / paste a long video',
            uploadMeta: 'Paste a course URL',
            uploadSource: 'https://course.example.com/attention-lecture',
            uploadHint: 'Identifying long-video source',
            uploadQueued: 'Notes, transcript, key moments',
            uploadSubtitle: 'URL detected',
            uploadTitle: 'Course lecture: attention mechanisms',
            uploadType: 'Learning material · public link',
            uploadDuration: '1:12:44 video',
            uploadDecision: 'Ready for study-note generation',
            uploadProgress: 'Source check in progress',
            uploadTags: ['Public link', 'Long lecture', 'Transcript', 'Key moments'],
            processing: 'Processing the video',
            processingMeta: 'Course lecture identified',
            processingMaterial: 'Long lecture · note-first route',
            processingStageTranscript: 'Transcript and subtitles',
            processingStageTranscriptStatus: 'Done',
            processingStageFrames: 'Key moments',
            processingStageFramesStatus: 'Running',
            processingStageNotes: 'Study notes',
            processingStageNotesStatus: 'Next',
            processingProgress: 'Processing 64%',
            processingHint: 'Preparing reviewable source material',
            study: 'Study beside the video',
            studyTime: '18:42',
            studyVideoLabel: 'Video',
            studyTranscriptLabel: 'Transcript',
            studyCaption: '"Attention narrows what each token compares."',
            studyNoteArea: 'Note editor',
            studyNoteTitleLabel: 'Note title',
            studyNoteTitle: 'Note title',
            studyChapterLabel: 'Chapter title',
            studyChapterTitle: 'Chapter title',
            studyNoteContentLabel: 'Note content',
            studyConclusion: 'Note content',
            studyAnchorLabel: 'Source anchor',
            studyAnchor: '18:42 source anchor',
            export: 'Export',
            exportFileCount: '4 files',
            exportMediaTitle: 'Video and audio',
            exportMediaVideo: 'Video file',
            exportMediaVideoFormat: '.mp4',
            exportMediaVideoHint: 'source video',
            exportMediaAudio: 'Audio track',
            exportMediaAudioFormat: '.mp3',
            exportMediaAudioHint: 'clean audio',
            exportMediaSubtitles: 'Subtitles',
            exportMediaSubtitlesFormat: '.srt',
            exportMediaSubtitlesHint: 'timed text',
            exportMediaFrames: 'Key frames',
            exportMediaFramesFormat: '.jpg',
            exportMediaFramesHint: 'visual anchors',
            exportNotesTitle: 'Notes and review',
            exportNotesMarkdown: 'Markdown',
            exportNotesMarkdownFormat: '.md',
            exportNotesMarkdownHint: 'editable note',
            exportNotesPdf: 'PDF',
            exportNotesPdfFormat: '.pdf',
            exportNotesPdfHint: 'reading copy',
            exportNotesFeishu: 'Feishu',
            exportNotesFeishuFormat: 'doc',
            exportNotesFeishuHint: 'workspace share',
            exportNotesPackage: 'Study note package',
            exportNotesPackageFormat: '.zip',
            exportNotesPackageHint: 'note bundle',
            finalNote: 'Ready to keep studying later.',
        },
        workflow: {
            eyebrow: 'Before / After',
            title: 'Study with notes ready, not with a pause button under your finger.',
            desc: 'The video stays central. FluentFlow removes the note-taking drag around it.',
            beforeTitle: 'Before',
            afterTitle: 'After',
            beforeItems: [
                ['Open a long video', 'You must decide what to capture from the first minute.'],
                ['Pause and rewind', 'One missed sentence breaks attention and sends you back.'],
                ['Clean the note later', 'After watching, chapters and examples still need manual cleanup.'],
            ],
            afterItems: [
                ['Generate notes first', 'Chapters, subtitles, and key moments are prepared upfront.'],
                ['Study with the video', 'Focus on the lesson and revisit the source only when needed.'],
                ['Fix a few details', 'Correct the small number of uncertain recognition or wording issues.'],
            ],
        },
        quality: {
            eyebrow: 'What quality means',
            title: 'Not a summary. A reviewable study asset.',
            desc: 'Structure, source checks, key moments, export.',
            items: [
                ['Structured chapters', 'Concepts, examples, and conclusions are shaped before you start watching.'],
                ['Important reasoning', 'Key steps stay visible instead of being flattened into a generic summary.'],
                ['Transcript review', 'Subtitles and transcript stay available so the note can be checked against source.'],
                ['Conservative correction', 'Accepted transcript fixes can show original text, corrected text, reason, confidence, and time.'],
                ['Key moments', 'When local video is available, visual anchors help you return to formulas, code, slides, or screens.'],
                ['Exportable result', 'Markdown, PDF, and Feishu exports turn the result into a lasting study asset.'],
            ],
        },
        sources: {
            eyebrow: 'Source coverage',
            title: 'Courses, lectures, recordings, files, and supported public links.',
            desc: 'Local upload and subtitle files are most reliable. Public platforms may restrict access.',
            items: {
                courses: 'Courses',
                lectures: 'Lectures',
                recordings: 'Screen recordings',
                localMedia: 'Local video or audio',
                subtitles: 'Subtitle files',
                links: 'Supported public links',
            },
        },
        output: {
            eyebrow: 'What you keep',
            title: 'A record you can study, review, and export.',
            desc: 'A reusable place for notes, transcript, visuals, records, and exports.',
            items: [
                ['Prepared note', 'Read the structure first, then study the video with better questions.'],
                ['Transcript and subtitles', 'Keep source text for unclear audio and recognition errors.'],
                ['Key visuals', 'Use important frames as review anchors when video evidence is available.'],
                ['Processing record', 'Running, failed, completed, downloads, and retries stay in one place.'],
            ],
        },
        cta: {
            eyebrow: 'Start with one real video',
            title: 'Give FluentFlow the next video you want to learn.',
            desc: 'Generate the note first. Study with the source beside it.',
            primary: 'Start processing',
            secondary: 'View processing records',
        },
    },
    zh: {
        nav: {
            studyFlow: '学习流程',
            noteQuality: '笔记质量',
            sources: '来源类型',
            openApp: '打开应用',
            startVideo: '开始处理',
            startShort: '开始',
        },
        controls: {
            languageLabel: '语言',
            themeLabel: '切换深色模式',
            switchToEnglish: '切换首页语言为英文',
            switchToChinese: '切换首页语言为中文',
            useLight: '使用明亮模式',
            useDark: '使用暗黑模式',
        },
        hero: {
            eyebrow: '长视频学习笔记',
            title: '先把长视频变成可以学习的笔记。',
            desc: '上传课程、讲座、录屏或视频链接。FluentFlow 先准备笔记、字幕/转录和关键画面。',
            primary: '开始处理',
            secondary: '查看学习流程',
            note: '',
        },
        heroVisual: {
            label: '动态产品演示：输入长视频，处理素材，对照笔记学习，再导出复查资产',
            path: 'fluentflow.app/video-note',
            inputStep: '输入',
            processingStep: '处理中',
            studyStep: '学习 / 复查',
            exportStep: '导出',
            upload: '上传或粘贴长视频',
            uploadMeta: '粘贴课程链接',
            uploadSource: 'https://course.example.com/attention-lecture',
            uploadHint: '正在识别长视频来源',
            uploadQueued: '笔记、转录、关键画面',
            uploadSubtitle: '已识别链接',
            uploadTitle: '课程讲座：注意力机制',
            uploadType: '学习材料 · 公开视频链接',
            uploadDuration: '1:12:44 视频',
            uploadDecision: '可生成学习笔记',
            uploadProgress: '正在检查来源',
            uploadTags: ['来源链接', '长视频', '字幕/转录', '关键画面'],
            processing: '正在处理视频',
            processingMeta: '已识别课程讲座',
            processingMaterial: '长讲座 · 先生成笔记路线',
            processingStageTranscript: '转录和字幕',
            processingStageTranscriptStatus: '完成',
            processingStageFrames: '关键画面',
            processingStageFramesStatus: '进行中',
            processingStageNotes: '学习笔记',
            processingStageNotesStatus: '下一步',
            processingProgress: '处理 64%',
            processingHint: '正在准备可复查的来源材料',
            study: '对照视频学习',
            studyTime: '18:42',
            studyVideoLabel: '视频区域',
            studyTranscriptLabel: '字幕',
            studyCaption: '“注意力会收窄每个 token 需要比较的范围。”',
            studyNoteArea: '笔记编辑区',
            studyNoteTitleLabel: '笔记标题',
            studyNoteTitle: '笔记标题',
            studyChapterLabel: '章节标题',
            studyChapterTitle: '章节标题',
            studyNoteContentLabel: '笔记内容',
            studyConclusion: '笔记内容',
            studyAnchorLabel: '来源锚点',
            studyAnchor: '18:42 来源锚点',
            export: '导出',
            exportFileCount: '4 项',
            exportMediaTitle: '视频和音频',
            exportMediaVideo: '视频文件',
            exportMediaVideoFormat: '.mp4',
            exportMediaVideoHint: '原视频',
            exportMediaAudio: '音频轨道',
            exportMediaAudioFormat: '.mp3',
            exportMediaAudioHint: '音频',
            exportMediaSubtitles: '字幕',
            exportMediaSubtitlesFormat: '.srt',
            exportMediaSubtitlesHint: '时间轴字幕',
            exportMediaFrames: '关键画面',
            exportMediaFramesFormat: '.jpg',
            exportMediaFramesHint: '画面锚点',
            exportNotesTitle: '笔记相关',
            exportNotesMarkdown: 'Markdown',
            exportNotesMarkdownFormat: '.md',
            exportNotesMarkdownHint: '可编辑笔记',
            exportNotesPdf: 'PDF',
            exportNotesPdfFormat: '.pdf',
            exportNotesPdfHint: '阅读版',
            exportNotesFeishu: '飞书',
            exportNotesFeishuFormat: 'doc',
            exportNotesFeishuHint: '协作页面',
            exportNotesPackage: '学习笔记包',
            exportNotesPackageFormat: '.zip',
            exportNotesPackageHint: '学习资产包',
            finalNote: '之后可以继续复习。',
        },
        workflow: {
            eyebrow: '前后对比',
            title: '先有笔记再看视频，不再被暂停键牵着走。',
            desc: '视频仍是主线。FluentFlow 先拿掉机械记笔记的拖累。',
            beforeTitle: '以前',
            afterTitle: '现在',
            beforeItems: [
                ['打开一条长视频', '从第一分钟开始就要判断哪些内容值得记。'],
                ['频繁暂停倒回', '漏掉一句话就会打断注意力，再拖回去重听。'],
                ['看完还要整理', '章节、例子和格式仍然需要手动清理。'],
            ],
            afterItems: [
                ['先生成笔记', '章节、字幕和关键画面提前准备好。'],
                ['对着视频学习', '把注意力放回课程，只在需要时回查来源。'],
                ['修少数细节', '只修正少量识别或措辞不确定的地方。'],
            ],
        },
        quality: {
            eyebrow: '什么才算高质量',
            title: '不是摘要，而是可复查的学习资产。',
            desc: '结构、来源、关键画面和导出。',
            items: [
                ['结构化章节', '概念、例子和结论会在你开始看视频前整理出来。'],
                ['关键推理保留', '重要步骤不会被压扁成泛泛总结。'],
                ['字幕/转录可复查', '原始字幕和转录保留，方便核对听不清或识别错误的地方。'],
                ['保守字幕纠错', '已接受的修正可展示原文、修正文、原因、置信度和时间点。'],
                ['关键画面', '本地视频可用时，重要画面会成为公式、代码、幻灯片或屏幕内容的复查锚点。'],
                ['结果可导出', 'Markdown、PDF 和飞书导出可以把结果留下来作为学习资产。'],
            ],
        },
        sources: {
            eyebrow: '来源覆盖',
            title: '课程、讲座、录屏、文件和支持的公开视频链接。',
            desc: '本地上传和字幕文件最稳定。公开视频平台可能限制访问。',
            items: {
                courses: '课程',
                lectures: '讲座',
                recordings: '屏幕录制',
                localMedia: '本地视频或音频',
                subtitles: '字幕文件',
                links: '支持的公开视频链接',
            },
        },
        output: {
            eyebrow: '最后留下什么',
            title: '一份可以学习、复查和导出的记录。',
            desc: '笔记、字幕、画面、处理记录和导出入口都留在一处。',
            items: [
                ['准备好的笔记', '先读结构，再带着更清楚的问题看视频。'],
                ['字幕和转录', '为听不清和识别错误的地方保留来源文本。'],
                ['关键画面', '视频证据可用时，用重要帧作为复习锚点。'],
                ['处理记录', '运行中、失败、完成、下载和重试都在同一个入口。'],
            ],
        },
        cta: {
            eyebrow: '从一条真实视频开始',
            title: '把下一条想学的视频交给 FluentFlow。',
            desc: '先生成笔记，再对着来源学习和修正。',
            primary: '开始处理',
            secondary: '查看处理记录',
        },
    },
};
